name: Archive Test Branch

on: # This workflow should not be triggered by any event (manually run only)
  workflow_dispatch: {}

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Archive Branch
        uses: octokit/rest@v18
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          branch: 'test'  # Replace with the actual branch name to archive
          archived: true
