name: Archive Branch with Script

on: # This workflow should not be triggered by any event (manually run only)
  workflow_dispatch: {}

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{secrets.TOKEN}}
          branches: test
