name: Archive Branch with Script

on: # This workflow should not be triggered by any event (manually run only)
  workflow_dispatch: {}

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Archive Branch with Script
        uses: actions/github-script@v6
        with:
          script: |
            const octokit = new github({ token: process.env.TOKEN });
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const branchToArchive = 'test'; // Replace with your branch name

            octokit.repos.update({
              owner,
              repo,
              archived: true,
              branch: branchToArchive
            }).then(() => {
              console.log(`Branch '${branchToArchive}' archived successfully!`);
            }).catch(error => {
              console.error(error);
            });
